# Generated by Django 4.2.6 on 2023-10-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
    ]
